excluded:
  - dependencies
  - Decimus/Views/VideoView.swift
  - Decimus/Views/Components/PreviewView.swift
analyzer_rules:
  - unused_import

type_body_length:
  warning: 500
  error: 750
file_length:
  warning: 500
  error: 1000
