#!/usr/bin/env bash
# SPDX-FileCopyrightText: Copyright (c) 2024
# SPDX-License-Identifier: BSD-2-Clause
#
# Build moxygen and all its Facebook dependencies for macOS
# This creates a self-contained build in _moxygen_build/
#
set -e

# Get correct directory (where this script lives)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd -P)"
MOXYGEN_DIR="$SCRIPT_DIR/moxygen"
BUILD_SCRATCH="$SCRIPT_DIR/_moxygen_build"
INSTALL_PREFIX="$BUILD_SCRATCH/installed"

# Build configuration
BUILD_TYPE="${BUILD_TYPE:-RelWithDebInfo}"
NUM_JOBS="${NUM_JOBS:-$(sysctl -n hw.ncpu)}"
VERBOSE="${VERBOSE:-}"

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --clean)
            echo "Cleaning build directory..."
            rm -rf "$BUILD_SCRATCH"
            shift
            ;;
        --verbose|-v)
            VERBOSE="-v"
            shift
            ;;
        --debug)
            BUILD_TYPE="Debug"
            shift
            ;;
        --release)
            BUILD_TYPE="Release"
            shift
            ;;
        --jobs=*)
            NUM_JOBS="${1#*=}"
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --clean       Clean build directory before building"
            echo "  --verbose,-v  Verbose output"
            echo "  --debug       Build with Debug configuration"
            echo "  --release     Build with Release configuration"
            echo "  --jobs=N      Number of parallel jobs (default: CPU count)"
            echo "  --help,-h     Show this help"
            echo ""
            echo "Build output will be in: $BUILD_SCRATCH"
            echo "Installed libraries in:  $INSTALL_PREFIX"
            exit 0
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

echo "=== Moxygen Build Script ==="
echo "Moxygen source: $MOXYGEN_DIR"
echo "Build scratch:  $BUILD_SCRATCH"
echo "Install prefix: $INSTALL_PREFIX"
echo "Build type:     $BUILD_TYPE"
echo "Parallel jobs:  $NUM_JOBS"
echo ""

# Verify moxygen directory exists
if [ ! -d "$MOXYGEN_DIR" ]; then
    echo "ERROR: moxygen directory not found at $MOXYGEN_DIR"
    echo "Please ensure the moxygen submodule is initialized:"
    echo "  git submodule update --init dependencies/moxygen"
    exit 1
fi

# Verify getdeps.py exists
GETDEPS="$MOXYGEN_DIR/build/fbcode_builder/getdeps.py"
if [ ! -f "$GETDEPS" ]; then
    echo "ERROR: getdeps.py not found at $GETDEPS"
    exit 1
fi

# Create build directory
mkdir -p "$BUILD_SCRATCH"

echo "=== Building moxygen and dependencies ==="
echo "This will download and build: ninja, cmake, zlib, zstd, boost, fmt, gflags, glog,"
echo "  openssl, folly, fizz, mvfst, wangle, proxygen, and moxygen itself."
echo ""
echo "First run may take 30-60 minutes depending on your machine."
echo ""

# Run the build
cd "$MOXYGEN_DIR"
python3 "$GETDEPS" build moxygen \
    --scratch-path "$BUILD_SCRATCH" \
    --install-prefix "$INSTALL_PREFIX" \
    --no-tests \
    --build-type "$BUILD_TYPE" \
    --num-jobs "$NUM_JOBS" \
    $VERBOSE

BUILD_STATUS=$?

if [ $BUILD_STATUS -eq 0 ]; then
    echo ""
    echo "=== Generating environment script ==="

    # Generate environment script for running moxygen binaries
    ENV_SCRIPT="$SCRIPT_DIR/moxygen-env.sh"
    cat > "$ENV_SCRIPT" << 'ENVEOF'
#!/usr/bin/env bash
# Generated by build-moxygen.sh
# Source this file to set up environment for running moxygen binaries
# Usage: source moxygen-env.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
INSTALL_PREFIX="$SCRIPT_DIR/_moxygen_build/installed"

# Build DYLD_LIBRARY_PATH from all installed lib directories
MOXYGEN_LIB_PATH=""
for libdir in "$INSTALL_PREFIX"/*/lib; do
    if [ -d "$libdir" ]; then
        if [ -z "$MOXYGEN_LIB_PATH" ]; then
            MOXYGEN_LIB_PATH="$libdir"
        else
            MOXYGEN_LIB_PATH="$MOXYGEN_LIB_PATH:$libdir"
        fi
    fi
done

export DYLD_LIBRARY_PATH="$MOXYGEN_LIB_PATH${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
export PATH="$INSTALL_PREFIX/moxygen/bin:$PATH"

# CMake prefix path for building against moxygen
export MOXYGEN_CMAKE_PREFIX_PATH="$INSTALL_PREFIX/moxygen"

echo "Moxygen environment configured:"
echo "  PATH includes: $INSTALL_PREFIX/moxygen/bin"
echo "  DYLD_LIBRARY_PATH configured for all dependencies"
echo "  MOXYGEN_CMAKE_PREFIX_PATH=$MOXYGEN_CMAKE_PREFIX_PATH"
ENVEOF
    chmod +x "$ENV_SCRIPT"

    # Generate CMake toolchain/config file for easier integration
    CMAKE_CONFIG="$SCRIPT_DIR/moxygen-cmake-paths.cmake"
    cat > "$CMAKE_CONFIG" << 'CMAKEEOF'
# Generated by build-moxygen.sh
# Include this in your CMake project to find moxygen and dependencies
# Usage: include(${CMAKE_CURRENT_LIST_DIR}/dependencies/moxygen-cmake-paths.cmake)

# Get the directory where this cmake file is located
get_filename_component(_MOXYGEN_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
set(_MOXYGEN_INSTALL_DIR "${_MOXYGEN_CMAKE_DIR}/_moxygen_build/installed")

set(MOXYGEN_ROOT "${_MOXYGEN_INSTALL_DIR}/moxygen")
set(MOXYGEN_INCLUDE_DIR "${MOXYGEN_ROOT}/include")
set(MOXYGEN_LIB_DIR "${MOXYGEN_ROOT}/lib")

# Add all dependency prefixes to CMAKE_PREFIX_PATH
# Using glob to find all installed packages (handles hash suffixes)
file(GLOB _MOXYGEN_PKG_DIRS "${_MOXYGEN_INSTALL_DIR}/*")
foreach(_pkg_dir ${_MOXYGEN_PKG_DIRS})
    if(IS_DIRECTORY "${_pkg_dir}")
        list(APPEND CMAKE_PREFIX_PATH "${_pkg_dir}")
    endif()
endforeach()

# Remove duplicates
list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)

message(STATUS "Moxygen paths configured from: ${MOXYGEN_ROOT}")

# Cleanup temporary variables
unset(_MOXYGEN_CMAKE_DIR)
unset(_MOXYGEN_INSTALL_DIR)
unset(_MOXYGEN_PKG_DIRS)
unset(_pkg_dir)
CMAKEEOF

    echo ""
    echo "=== Build Complete ==="
    echo ""
    echo "Installed to: $INSTALL_PREFIX"
    echo ""
    echo "Generated files:"
    echo "  $ENV_SCRIPT        - Source to run moxygen binaries"
    echo "  $CMAKE_CONFIG      - Include in CMake for builds"
    echo ""
    echo "To run moxygen binaries:"
    echo "  source $ENV_SCRIPT"
    echo "  moqrelayserver --help"
    echo ""
    echo "To use in CMake:"
    echo "  include($CMAKE_CONFIG)"
    echo ""

    # Show moxygen libraries
    echo "Moxygen libraries:"
    ls -la "$INSTALL_PREFIX/moxygen/lib/"*.a 2>/dev/null || echo "  (none found)"
    echo ""
    echo "Moxygen binaries:"
    ls "$INSTALL_PREFIX/moxygen/bin/" 2>/dev/null || echo "  (none found)"
else
    echo ""
    echo "=== Build Failed ==="
    echo "Check the output above for errors."
    exit $BUILD_STATUS
fi
