#!/usr/bin/env bash
# Generated by build-moxygen.sh
# Source this file to set up environment for running moxygen binaries
# Usage: source moxygen-env.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
INSTALL_PREFIX="$SCRIPT_DIR/_moxygen_build/installed"

# Build DYLD_LIBRARY_PATH from all installed lib directories
MOXYGEN_LIB_PATH=""
for libdir in "$INSTALL_PREFIX"/*/lib; do
    if [ -d "$libdir" ]; then
        if [ -z "$MOXYGEN_LIB_PATH" ]; then
            MOXYGEN_LIB_PATH="$libdir"
        else
            MOXYGEN_LIB_PATH="$MOXYGEN_LIB_PATH:$libdir"
        fi
    fi
done

export DYLD_LIBRARY_PATH="$MOXYGEN_LIB_PATH${DYLD_LIBRARY_PATH:+:$DYLD_LIBRARY_PATH}"
export PATH="$INSTALL_PREFIX/moxygen/bin:$PATH"

# CMake prefix path for building against moxygen
export MOXYGEN_CMAKE_PREFIX_PATH="$INSTALL_PREFIX/moxygen"

echo "Moxygen environment configured:"
echo "  PATH includes: $INSTALL_PREFIX/moxygen/bin"
echo "  DYLD_LIBRARY_PATH configured for all dependencies"
echo "  MOXYGEN_CMAKE_PREFIX_PATH=$MOXYGEN_CMAKE_PREFIX_PATH"
