# Generated by build-moxygen.sh
# Include this in your CMake project to find moxygen and dependencies
# Usage: include(${CMAKE_CURRENT_LIST_DIR}/dependencies/moxygen-cmake-paths.cmake)

# Get the directory where this cmake file is located
get_filename_component(_MOXYGEN_CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" DIRECTORY)
set(_MOXYGEN_INSTALL_DIR "${_MOXYGEN_CMAKE_DIR}/_moxygen_build/installed")

set(MOXYGEN_ROOT "${_MOXYGEN_INSTALL_DIR}/moxygen")
set(MOXYGEN_INCLUDE_DIR "${MOXYGEN_ROOT}/include")
set(MOXYGEN_LIB_DIR "${MOXYGEN_ROOT}/lib")

# Add all dependency prefixes to CMAKE_PREFIX_PATH
# Using glob to find all installed packages (handles hash suffixes)
file(GLOB _MOXYGEN_PKG_DIRS "${_MOXYGEN_INSTALL_DIR}/*")
foreach(_pkg_dir ${_MOXYGEN_PKG_DIRS})
    if(IS_DIRECTORY "${_pkg_dir}")
        list(APPEND CMAKE_PREFIX_PATH "${_pkg_dir}")
    endif()
endforeach()

# Remove duplicates
list(REMOVE_DUPLICATES CMAKE_PREFIX_PATH)

message(STATUS "Moxygen paths configured from: ${MOXYGEN_ROOT}")

# Cleanup temporary variables
unset(_MOXYGEN_CMAKE_DIR)
unset(_MOXYGEN_INSTALL_DIR)
unset(_MOXYGEN_PKG_DIRS)
unset(_pkg_dir)
